import { contextBridge, ipcRenderer } from 'electron';

// Expose typed API to renderer
contextBridge.exposeInMainWorld('electronAPI', {
  // ─── Platform info ──────────────────────────────────────────────
  platform: process.platform,  // 'darwin' | 'win32' | 'linux'

  // ─── Window Controls ─────────────────────────────────────────────
  window: {
    minimize: () => ipcRenderer.send('window:minimize'),
    maximize: () => ipcRenderer.send('window:maximize'),
    close: () => ipcRenderer.send('window:close'),
    quit: () => ipcRenderer.send('window:quit'),
    isMaximized: () => ipcRenderer.invoke('window:isMaximized'),
  },

  // ─── Shell ───────────────────────────────────────────────────────
  shell: {
    openExternal: (url: string) => ipcRenderer.send('shell:openExternal', url),
    openPath: (filePath: string) => ipcRenderer.invoke('shell:openPath', filePath),
    openInApp: (url: string) => ipcRenderer.invoke('shell:openInApp', url),
  },

  // ─── Util ───────────────────────────────────────────────────────
  util: {
    fetchUrl: (args: { url: string }) => ipcRenderer.invoke('util:fetchUrl', args),
  },

  // ─── Login / Account ─────────────────────────────────────────────
  login: {
    loginQR: (tempId: string) => ipcRenderer.invoke('login:qr', { tempId }),
    loginQRAbort: (tempId: string) => ipcRenderer.invoke('login:qr:abort', { tempId }),
    loginCookies: (imei: string, cookies: string, userAgent: string) =>
      ipcRenderer.invoke('login:cookies', { imei, cookies, userAgent }),
    loginAuth: (authJson: string) => ipcRenderer.invoke('login:auth', { authJson }),
    connectAccount: (auth: unknown) => ipcRenderer.invoke('login:connect', { auth }),
    disconnectAccount: (zaloId: string) => ipcRenderer.invoke('login:disconnect', { zaloId }),
    disconnectAll: () => ipcRenderer.invoke('login:disconnectAll'),
    getAccounts: () => ipcRenderer.invoke('login:getAccounts'),
    removeAccount: (zaloId: string) => ipcRenderer.invoke('login:removeAccount', { zaloId }),
    checkHealth: (zaloIds: string | string[]) => ipcRenderer.invoke('login:checkHealth', { zaloIds }),
    requestOldMessages: (zaloId: string) => ipcRenderer.invoke('login:requestOldMessages', { zaloId }),
  },

  // ─── Zalo API ────────────────────────────────────────────────────
  zalo: {
    sendMessage: (params: unknown) => ipcRenderer.invoke('zalo:sendMessage', params),
    sendImage: (params: unknown) => ipcRenderer.invoke('zalo:sendImage', params),
    sendImages: (params: unknown) => ipcRenderer.invoke('zalo:sendImages', params),
    sendFile: (params: unknown) => ipcRenderer.invoke('zalo:sendFile', params),
    sendSticker: (params: unknown) => ipcRenderer.invoke('zalo:sendSticker', params),
    sendVoice: (params: unknown) => ipcRenderer.invoke('zalo:sendVoice', params),
    sendVideo: (params: unknown) => ipcRenderer.invoke('zalo:sendVideo', params),
    sendLink: (params: unknown) => ipcRenderer.invoke('zalo:sendLink', params),
    sendCard: (params: unknown) => ipcRenderer.invoke('zalo:sendCard', params),
    undoMessage: (params: unknown) => ipcRenderer.invoke('zalo:undoMessage', params),
    deleteMessage: (params: unknown) => ipcRenderer.invoke('zalo:deleteMessage', params),
    deleteChat: (params: unknown) => ipcRenderer.invoke('zalo:deleteChat', params),
    addReaction: (params: unknown) => ipcRenderer.invoke('zalo:addReaction', params),
    forwardMessage: (params: unknown) => ipcRenderer.invoke('zalo:forwardMessage', params),
    getFriends: (auth: unknown) => ipcRenderer.invoke('zalo:getFriends', { auth }),
    getGroups: (auth: unknown) => ipcRenderer.invoke('zalo:getGroups', { auth }),
    getUserInfo: (params: unknown) => ipcRenderer.invoke('zalo:getUserInfo', params),
    getContext: (params: unknown) => ipcRenderer.invoke('zalo:getContext', params),
    findUser: (params: unknown) => ipcRenderer.invoke('zalo:findUser', params),
    sendFriendRequest: (params: unknown) => ipcRenderer.invoke('zalo:sendFriendRequest', params),
    acceptFriendRequest: (params: unknown) => ipcRenderer.invoke('zalo:acceptFriendRequest', params),
    rejectFriendRequest: (params: unknown) => ipcRenderer.invoke('zalo:rejectFriendRequest', params),
    undoFriendRequest: (params: unknown) => ipcRenderer.invoke('zalo:undoFriendRequest', params),
    removeFriend: (params: unknown) => ipcRenderer.invoke('zalo:removeFriend', params),
    getSentFriendRequests: (auth: unknown) => ipcRenderer.invoke('zalo:getSentFriendRequests', { auth }),
    getFriendRequestStatus: (params: unknown) => ipcRenderer.invoke('zalo:getFriendRequestStatus', params),
    getFriendRecommendations: (auth: unknown) => ipcRenderer.invoke('zalo:getFriendRecommendations', { auth }),
    getAliasList: (params: unknown) => ipcRenderer.invoke('zalo:getAliasList', params),
    blockUser: (params: unknown) => ipcRenderer.invoke('zalo:blockUser', params),
    unblockUser: (params: unknown) => ipcRenderer.invoke('zalo:unblockUser', params),
    getRelatedFriendGroup: (params: unknown) => ipcRenderer.invoke('zalo:getRelatedFriendGroup', params),
    createGroup: (params: unknown) => ipcRenderer.invoke('zalo:createGroup', params),
    getGroupInfo: (params: unknown) => ipcRenderer.invoke('zalo:getGroupInfo', params),
    addUserToGroup: (params: unknown) => ipcRenderer.invoke('zalo:addUserToGroup', params),
    removeUserFromGroup: (params: unknown) => ipcRenderer.invoke('zalo:removeUserFromGroup', params),
    leaveGroup: (params: unknown) => ipcRenderer.invoke('zalo:leaveGroup', params),
    changeGroupName: (params: unknown) => ipcRenderer.invoke('zalo:changeGroupName', params),
    changeGroupAvatar: (params: unknown) => ipcRenderer.invoke('zalo:changeGroupAvatar', params),
    changeGroupOwner: (params: unknown) => ipcRenderer.invoke('zalo:changeGroupOwner', params),
    disperseGroup: (params: unknown) => ipcRenderer.invoke('zalo:disperseGroup', params),
    addGroupDeputy: (params: unknown) => ipcRenderer.invoke('zalo:addGroupDeputy', params),
    removeGroupDeputy: (params: unknown) => ipcRenderer.invoke('zalo:removeGroupDeputy', params),
    getGroupMembersInfo: (params: unknown) => ipcRenderer.invoke('zalo:getGroupMembersInfo', params),
    addGroupBlockedMember: (params: unknown) => ipcRenderer.invoke('zalo:addGroupBlockedMember', params),
    removeGroupBlockedMember: (params: unknown) => ipcRenderer.invoke('zalo:removeGroupBlockedMember', params),
    getGroupBlockedMember: (params: unknown) => ipcRenderer.invoke('zalo:getGroupBlockedMember', params),
    inviteUserToGroups: (params: unknown) => ipcRenderer.invoke('zalo:inviteUserToGroups', params),
    updateGroupSettings: (params: unknown) => ipcRenderer.invoke('zalo:updateGroupSettings', params),
    getGroupLinkDetail: (params: unknown) => ipcRenderer.invoke('zalo:getGroupLinkDetail', params),
    getGroupLinkInfo: (params: unknown) => ipcRenderer.invoke('zalo:getGroupLinkInfo', params),
    enableGroupLink: (params: unknown) => ipcRenderer.invoke('zalo:enableGroupLink', params),
    disableGroupLink: (params: unknown) => ipcRenderer.invoke('zalo:disableGroupLink', params),
    getPendingGroupMembers: (params: unknown) => ipcRenderer.invoke('zalo:getPendingGroupMembers', params),
    getMessageHistory: (params: unknown) => ipcRenderer.invoke('zalo:getMessageHistory', params),
    getGroupChatHistory: (params: unknown) => ipcRenderer.invoke('zalo:getGroupChatHistory', params),
    getPinConversations: (auth: unknown) => ipcRenderer.invoke('zalo:getPinConversations', { auth }),
    setPinConversation: (params: unknown) => ipcRenderer.invoke('zalo:setPinConversation', params),
    setMute: (params: unknown) => ipcRenderer.invoke('zalo:setMute', params),
    keepAlive: (auth: unknown) => ipcRenderer.invoke('zalo:keepAlive', { auth }),
    getLabels: (params: unknown) => ipcRenderer.invoke('zalo:getLabels', params),
    updateLabels: (params: unknown) => ipcRenderer.invoke('zalo:updateLabels', params),
    changeFriendAlias: (params: unknown) => ipcRenderer.invoke('zalo:changeFriendAlias', params),
    getStickers: (params: unknown) => ipcRenderer.invoke('zalo:getStickers', params),
    getStickersDetail: (params: unknown) => ipcRenderer.invoke('zalo:getStickersDetail', params),
    getStickerCategoryDetail: (params: unknown) => ipcRenderer.invoke('zalo:getStickerCategoryDetail', params),
    addUnreadMark: (params: unknown) => ipcRenderer.invoke('zalo:addUnreadMark', params),
    removeUnreadMark: (params: unknown) => ipcRenderer.invoke('zalo:removeUnreadMark', params),
    createPoll: (params: unknown) => ipcRenderer.invoke('zalo:createPoll', params),
    getPollDetail: (params: unknown) => ipcRenderer.invoke('zalo:getPollDetail', params),
    lockPoll: (params: unknown) => ipcRenderer.invoke('zalo:lockPoll', params),
    doVotePoll: (params: unknown) => ipcRenderer.invoke('zalo:doVotePoll', params),
    addPollOption: (params: unknown) => ipcRenderer.invoke('zalo:addPollOption', params),
    uploadVideoThumb: (params: unknown) => ipcRenderer.invoke('zalo:uploadVideoThumb', params),
    uploadVideoFile: (params: unknown) => ipcRenderer.invoke('zalo:uploadVideoFile', params),
    uploadVoiceFile: (params: unknown) => ipcRenderer.invoke('zalo:uploadVoiceFile', params),
    getQuickMessageList: (params: unknown) => ipcRenderer.invoke('zalo:getQuickMessageList', params),
    addQuickMessage: (params: unknown) => ipcRenderer.invoke('zalo:addQuickMessage', params),
    updateQuickMessage: (params: unknown) => ipcRenderer.invoke('zalo:updateQuickMessage', params),
    removeQuickMessage: (params: unknown) => ipcRenderer.invoke('zalo:removeQuickMessage', params),
    createNote: (params: unknown) => ipcRenderer.invoke('zalo:createNote', params),
    editNote: (params: unknown) => ipcRenderer.invoke('zalo:editNote', params),
    createReminder: (params: unknown) => ipcRenderer.invoke('zalo:createReminder', params),
    editReminder: (params: unknown) => ipcRenderer.invoke('zalo:editReminder', params),
    removeReminder: (params: unknown) => ipcRenderer.invoke('zalo:removeReminder', params),
    getListReminder: (params: unknown) => ipcRenderer.invoke('zalo:getListReminder', params),
    getReminder: (params: unknown) => ipcRenderer.invoke('zalo:getReminder', params),
    sendSeenEvent: (params: unknown) => ipcRenderer.invoke('zalo:sendSeenEvent', params),
    sendBankCard: (params: unknown) => ipcRenderer.invoke('zalo:sendBankCard', params),
  },

    db: {
    getMessages: (params: unknown) => ipcRenderer.invoke('db:getMessages', params),
    getMessagesAround: (params: unknown) => ipcRenderer.invoke('db:getMessagesAround', params),
    getContacts: (zaloId: string) => ipcRenderer.invoke('db:getContacts', { zaloId }),
    searchMessages: (params: unknown) => ipcRenderer.invoke('db:searchMessages', params),
    getMediaMessages: (params: unknown) => ipcRenderer.invoke('db:getMediaMessages', params),
    getFileMessages: (params: unknown) => ipcRenderer.invoke('db:getFileMessages', params),
    getUnreadCount: (zaloId: string) => ipcRenderer.invoke('db:getUnreadCount', { zaloId }),
    markAsRead: (params: unknown) => ipcRenderer.invoke('db:markAsRead', params),
    markMessageRecalled: (params: unknown) => ipcRenderer.invoke('db:markMessageRecalled', params),
    deleteMessages: (params: unknown) => ipcRenderer.invoke('db:deleteMessages', params),
    updateContactProfile: (params: unknown) => ipcRenderer.invoke('db:updateContactProfile', params),
    updateAccountPhone: (params: unknown) => ipcRenderer.invoke('db:updateAccountPhone', params),
    updateReaction: (params: unknown) => ipcRenderer.invoke('db:updateReaction', params),
    updateLocalPaths: (params: unknown) => ipcRenderer.invoke('db:updateLocalPaths', params),
    getMessageById: (params: unknown) => ipcRenderer.invoke('db:getMessageById', params),
    getStoragePath: () => ipcRenderer.invoke('db:getStoragePath'),
    setStoragePath: (params: unknown) => ipcRenderer.invoke('db:setStoragePath', params),
    selectStorageFolder: () => ipcRenderer.invoke('db:selectStorageFolder'),
    getFriends: (params: unknown) => ipcRenderer.invoke('db:getFriends', params),
    saveFriends: (params: unknown) => ipcRenderer.invoke('db:saveFriends', params),
    isFriend: (params: unknown) => ipcRenderer.invoke('db:isFriend', params),
    getFriendRequests: (params: unknown) => ipcRenderer.invoke('db:getFriendRequests', params),
    saveFriendRequests: (params: unknown) => ipcRenderer.invoke('db:saveFriendRequests', params),
    upsertFriendRequest: (params: unknown) => ipcRenderer.invoke('db:upsertFriendRequest', params),
    removeFriendRequest: (params: unknown) => ipcRenderer.invoke('db:removeFriendRequest', params),
    addFriend: (params: unknown) => ipcRenderer.invoke('db:addFriend', params),
    removeFriend: (params: unknown) => ipcRenderer.invoke('db:removeFriend', params),
    deleteConversation: (params: unknown) => ipcRenderer.invoke('db:deleteConversation', params),
    getLinks: (params: unknown) => ipcRenderer.invoke('db:getLinks', params),
    saveLink: (params: unknown) => ipcRenderer.invoke('db:saveLink', params),
    getGroupMembers: (params: unknown) => ipcRenderer.invoke('db:getGroupMembers', params),
    getAllGroupMembers: (params: unknown) => ipcRenderer.invoke('db:getAllGroupMembers', params),
    saveGroupMembers: (params: unknown) => ipcRenderer.invoke('db:saveGroupMembers', params),
    upsertGroupMember: (params: unknown) => ipcRenderer.invoke('db:upsertGroupMember', params),
    removeGroupMember: (params: unknown) => ipcRenderer.invoke('db:removeGroupMember', params),
    saveStickers: (params: unknown) => ipcRenderer.invoke('db:saveStickers', params),
    getStickerById: (params: unknown) => ipcRenderer.invoke('db:getStickerById', params),
    getRecentStickers: (params?: unknown) => ipcRenderer.invoke('db:getRecentStickers', params || {}),
    addRecentSticker: (params: unknown) => ipcRenderer.invoke('db:addRecentSticker', params),
    markStickerUnsupported: (params: unknown) => ipcRenderer.invoke('db:markStickerUnsupported', params),
    saveStickerPacks: (params: unknown) => ipcRenderer.invoke('db:saveStickerPacks', params),
    getStickerPacks: (params?: unknown) => ipcRenderer.invoke('db:getStickerPacks', params || {}),
    getStickersByPackId: (params: unknown) => ipcRenderer.invoke('db:getStickersByPackId', params),
    saveKeywordStickers: (params: unknown) => ipcRenderer.invoke('db:saveKeywordStickers', params),
    getKeywordStickers: (params: unknown) => ipcRenderer.invoke('db:getKeywordStickers', params),
    getStickersByIds: (params: unknown) => ipcRenderer.invoke('db:getStickersByIds', params),
    getAllCachedPackSummaries: (params?: unknown) => ipcRenderer.invoke('db:getAllCachedPackSummaries', params || {}),
    getPinnedMessages: (params: unknown) => ipcRenderer.invoke('db:getPinnedMessages', params),
    getMessagesByType: (params: unknown) => ipcRenderer.invoke('db:getMessagesByType', params),
    pinMessage: (params: unknown) => ipcRenderer.invoke('db:pinMessage', params),
    unpinMessage: (params: unknown) => ipcRenderer.invoke('db:unpinMessage', params),
    bringPinnedToTop: (params: unknown) => ipcRenderer.invoke('db:bringPinnedToTop', params),
    getLocalQuickMessages: (params: unknown) => ipcRenderer.invoke('db:getLocalQuickMessages', params),
    upsertLocalQuickMessage: (params: unknown) => ipcRenderer.invoke('db:upsertLocalQuickMessage', params),
    deleteLocalQuickMessage: (params: unknown) => ipcRenderer.invoke('db:deleteLocalQuickMessage', params),
    bulkReplaceLocalQuickMessages: (params: unknown) => ipcRenderer.invoke('db:bulkReplaceLocalQuickMessages', params),
    getAllLocalQuickMessages: () => ipcRenderer.invoke('db:getAllLocalQuickMessages'),
    cloneLocalQuickMessages: (params: unknown) => ipcRenderer.invoke('db:cloneLocalQuickMessages', params),
    setLocalQMActive: (params: unknown) => ipcRenderer.invoke('db:setLocalQMActive', params),
    setLocalQMOrder: (params: unknown) => ipcRenderer.invoke('db:setLocalQMOrder', params),

    // Local Labels
    getLocalLabels: (params: unknown) => ipcRenderer.invoke('db:getLocalLabels', params),
    upsertLocalLabel: (params: unknown) => ipcRenderer.invoke('db:upsertLocalLabel', params),
    deleteLocalLabel: (params: unknown) => ipcRenderer.invoke('db:deleteLocalLabel', params),
    cloneLocalLabels: (params: unknown) => ipcRenderer.invoke('db:cloneLocalLabels', params),
    getLocalLabelThreads: (params: unknown) => ipcRenderer.invoke('db:getLocalLabelThreads', params),
    assignLocalLabelToThread: (params: unknown) => ipcRenderer.invoke('db:assignLocalLabelToThread', params),
    removeLocalLabelFromThread: (params: unknown) => ipcRenderer.invoke('db:removeLocalLabelFromThread', params),
    getThreadLocalLabels: (params: unknown) => ipcRenderer.invoke('db:getThreadLocalLabels', params),
    setLocalLabelActive: (params: unknown) => ipcRenderer.invoke('db:setLocalLabelActive', params),
    setLocalLabelOrder: (params: unknown) => ipcRenderer.invoke('db:setLocalLabelOrder', params),

    setContactFlags: (params: unknown) => ipcRenderer.invoke('db:setContactFlags', params),
    getContactsWithFlags: (params: unknown) => ipcRenderer.invoke('db:getContactsWithFlags', params),
    setContactAlias: (params: unknown) => ipcRenderer.invoke('db:setContactAlias', params),

    // Message Drafts
    upsertDraft: (params: unknown) => ipcRenderer.invoke('db:upsertDraft', params),
    deleteDraft: (params: unknown) => ipcRenderer.invoke('db:deleteDraft', params),
    getDraft: (params: unknown) => ipcRenderer.invoke('db:getDraft', params),
    getDrafts: (params: unknown) => ipcRenderer.invoke('db:getDrafts', params),
    deleteOldDrafts: (params?: unknown) => ipcRenderer.invoke('db:deleteOldDrafts', params || {}),

    // Bank Cards
    getBankCards: (params: unknown) => ipcRenderer.invoke('db:getBankCards', params),
    upsertBankCard: (params: unknown) => ipcRenderer.invoke('db:upsertBankCard', params),
    deleteBankCard: (params: unknown) => ipcRenderer.invoke('db:deleteBankCard', params),

    // Local Pinned Conversations
    getLocalPinnedConversations: (params: unknown) => ipcRenderer.invoke('db:getLocalPinnedConversations', params),
    setLocalPinnedConversation: (params: unknown) => ipcRenderer.invoke('db:setLocalPinnedConversation', params),
    getPipelineStages: () => ipcRenderer.invoke('db:getPipelineStages'),
    savePipelineStage: (params: unknown) => ipcRenderer.invoke('db:savePipelineStage', params),
    deletePipelineStage: (params: unknown) => ipcRenderer.invoke('db:deletePipelineStage', params),
    updateContactPipelineStage: (params: unknown) => ipcRenderer.invoke('db:updateContactPipelineStage', params),
    getCalendarEventsByContact: (params: unknown) => ipcRenderer.invoke('db:getCalendarEventsByContact', params),
  },

  // ─── CRM ─────────────────────────────────────────────────────────
  crm: {
    getNotes: (params: unknown) => ipcRenderer.invoke('crm:getNotes', params),
    saveNote: (params: unknown) => ipcRenderer.invoke('crm:saveNote', params),
    deleteNote: (params: unknown) => ipcRenderer.invoke('crm:deleteNote', params),
    getContacts: (params: unknown) => ipcRenderer.invoke('crm:getContacts', params),
    getContactStats: (params: unknown) => ipcRenderer.invoke('crm:getContactStats', params),
    getCampaigns: (params: unknown) => ipcRenderer.invoke('crm:getCampaigns', params),
    saveCampaign: (params: unknown) => ipcRenderer.invoke('crm:saveCampaign', params),
    deleteCampaign: (params: unknown) => ipcRenderer.invoke('crm:deleteCampaign', params),
    cloneCampaign: (params: unknown) => ipcRenderer.invoke('crm:cloneCampaign', params),
    updateCampaignStatus: (params: unknown) => ipcRenderer.invoke('crm:updateCampaignStatus', params),
    addCampaignContacts: (params: unknown) => ipcRenderer.invoke('crm:addCampaignContacts', params),
    getCampaignContacts: (params: unknown) => ipcRenderer.invoke('crm:getCampaignContacts', params),
    getSendLog: (params: unknown) => ipcRenderer.invoke('crm:getSendLog', params),
    getQueueStatus: (params: unknown) => ipcRenderer.invoke('crm:getQueueStatus', params),
    getCampaignStats: (params: unknown) => ipcRenderer.invoke('crm:getCampaignStats', params),
    getActivityStats: (params: unknown) => ipcRenderer.invoke('crm:getActivityStats', params),
  },

  // ─── Analytics / Reporting ──────────────────────────────────────────
  analytics: {
    dashboardOverview:   (params: unknown) => ipcRenderer.invoke('analytics:dashboardOverview', params),
    messageVolume:       (params: unknown) => ipcRenderer.invoke('analytics:messageVolume', params),
    peakHours:           (params: unknown) => ipcRenderer.invoke('analytics:peakHours', params),
    contactGrowth:       (params: unknown) => ipcRenderer.invoke('analytics:contactGrowth', params),
    contactSegmentation: (params: unknown) => ipcRenderer.invoke('analytics:contactSegmentation', params),
    campaignComparison:  (params: unknown) => ipcRenderer.invoke('analytics:campaignComparison', params),
    friendRequests:      (params: unknown) => ipcRenderer.invoke('analytics:friendRequests', params),
    workflowAnalytics:   (params: unknown) => ipcRenderer.invoke('analytics:workflowAnalytics', params),
    aiAnalytics:         (params: unknown) => ipcRenderer.invoke('analytics:aiAnalytics', params),
    responseTime:        (params: unknown) => ipcRenderer.invoke('analytics:responseTime', params),
    labelUsage:          (params: unknown) => ipcRenderer.invoke('analytics:labelUsage', params),
  },

  // ─── File ────────────────────────────────────────────────────────
  file: {
    openDialog: (options: unknown) => ipcRenderer.invoke('file:openDialog', options),
    saveImage: (params: unknown) => ipcRenderer.invoke('file:saveImage', params),
    getAppDataPath: () => ipcRenderer.invoke('file:getAppDataPath'),
    openPath: (filePath: string) => ipcRenderer.invoke('file:openPath', filePath),
    showItemInFolder: (filePath: string) => ipcRenderer.invoke('file:showItemInFolder', filePath),
    saveAs: (params: unknown) => ipcRenderer.invoke('file:saveAs', params),
    saveTempBlob: (params: unknown) => ipcRenderer.invoke('file:saveTempBlob', params),
    getVideoMeta: (params: unknown) => ipcRenderer.invoke('file:getVideoMeta', params),
  },

  // ─── Workflow Engine ─────────────────────────────────────────────
    workflow: {
      list: () => ipcRenderer.invoke('workflow:list'),
      get: (id: string) => ipcRenderer.invoke('workflow:get', { id }),
      save: (workflow: any) => ipcRenderer.invoke('workflow:save', { workflow }),
      delete: (id: string) => ipcRenderer.invoke('workflow:delete', { id }),
      toggle: (id: string, enabled: boolean) => ipcRenderer.invoke('workflow:toggle', { id, enabled }),
      runManual: (id: string, triggerData?: any) => ipcRenderer.invoke('workflow:runManual', { id, triggerData }),
      getLogs: (id: string, limit?: number) => ipcRenderer.invoke('workflow:getLogs', { id, limit }),
      deleteLogs: (id: string) => ipcRenderer.invoke('workflow:deleteLogs', { id }),
      clone: (id: string, targetZaloId: string) => ipcRenderer.invoke('workflow:clone', { id, targetZaloId }),
      cloneAll: (sourceZaloId: string, targetZaloId: string) => ipcRenderer.invoke('workflow:cloneAll', { sourceZaloId, targetZaloId }),
  },

  // ─── App-level (badge, open thread) ─────────────────────────────
  app: {
    setBadge: (count: number) => ipcRenderer.send('app:setBadge', count),
    openThread: (params: { zaloId: string; threadId: string; threadType: number }) =>
      ipcRenderer.send('app:openThread', params),
    sendBadgeImage: (params: { dataUrl: string; count: number }) =>
      ipcRenderer.send('app:badgeImage', params),
    flashFrame: (active: boolean) => ipcRenderer.send('app:flashFrame', { active }),
  },

  // ─── Auto-update ─────────────────────────────────────────────────
  update: {
    download: () => ipcRenderer.send('update:download'),
    install:  () => ipcRenderer.send('update:install'),
  },

  // ─── Integration Hub ──────────────────────────────────────────────
  integration: {
    list:            () => ipcRenderer.invoke('integration:list'),
    get:             (id: string) => ipcRenderer.invoke('integration:get', { id }),
    save:            (integration: any) => ipcRenderer.invoke('integration:save', { integration }),
    delete:          (id: string) => ipcRenderer.invoke('integration:delete', { id }),
    toggle:          (id: string, enabled: boolean) => ipcRenderer.invoke('integration:toggle', { id, enabled }),
    test:            (id: string) => ipcRenderer.invoke('integration:test', { id }),
    execute:         (id: string, action: string, params?: any) => ipcRenderer.invoke('integration:execute', { id, action, params }),
    executeByType:   (type: string, action: string, params?: any) => ipcRenderer.invoke('integration:executeByType', { type, action, params }),
    getWebhookPort:  () => ipcRenderer.invoke('integration:getWebhookPort'),
  },

  // ─── AI Assistants ────────────────────────────────────────────────
  ai: {
    listAssistants:  () => ipcRenderer.invoke('ai:listAssistants'),
    getAssistant:    (id: string) => ipcRenderer.invoke('ai:getAssistant', { id }),
    getDefault:      () => ipcRenderer.invoke('ai:getDefault'),
    saveAssistant:   (assistant: any) => ipcRenderer.invoke('ai:saveAssistant', { assistant }),
    deleteAssistant: (id: string) => ipcRenderer.invoke('ai:deleteAssistant', { id }),
    testAssistant:   (id: string) => ipcRenderer.invoke('ai:testAssistant', { id }),
    getFiles:        (assistantId: string) => ipcRenderer.invoke('ai:getFiles', { assistantId }),
    uploadFile:      (assistantId: string, filePath: string) => ipcRenderer.invoke('ai:uploadFile', { assistantId, filePath }),
    removeFile:      (fileId: number) => ipcRenderer.invoke('ai:removeFile', { fileId }),
    suggest:         (assistantId: string, chatHistory: any[]) => ipcRenderer.invoke('ai:suggest', { assistantId, chatHistory }),
    chat:            (assistantId: string, messages: any[], structured?: boolean) => ipcRenderer.invoke('ai:chat', { assistantId, messages, structured }),
    getAccountAssistant:  (zaloId: string, role: string) => ipcRenderer.invoke('ai:getAccountAssistant', { zaloId, role }),
    setAccountAssistant:  (zaloId: string, role: string, assistantId: string | null) => ipcRenderer.invoke('ai:setAccountAssistant', { zaloId, role, assistantId }),
    getAccountAssistants: (zaloId: string) => ipcRenderer.invoke('ai:getAccountAssistants', { zaloId }),
    getUsageLogs:  (opts?: any) => ipcRenderer.invoke('ai:getUsageLogs', opts || {}),
    getUsageStats: (opts?: any) => ipcRenderer.invoke('ai:getUsageStats', opts || {}),
    fetchModels:   (params: unknown) => ipcRenderer.invoke('ai:fetchModels', params),
    analyzeContact: (params: { ownerZaloId: string; contactId: string }) => ipcRenderer.invoke('ai:analyzeContact', params),
    batchSummarizeContactNotes: (params: { ownerZaloId: string; contactId: string }) => ipcRenderer.invoke('ai:batchSummarizeContactNotes', params),
    suggestSmartTags: (params: { ownerZaloId: string; contactId: string }) => ipcRenderer.invoke('ai:suggestSmartTags', params),
  },

  // ─── Tunnel ───────────────────────────────────────────────────────
  tunnel: {
    start:  () => ipcRenderer.invoke('tunnel:start'),
    stop:   () => ipcRenderer.invoke('tunnel:stop'),
    status: () => ipcRenderer.invoke('tunnel:status'),
  },

  // ─── Employee Management ───────────────────────────────────────────
  employee: {
    list:               () => ipcRenderer.invoke('employee:list'),
    getById:            (employeeId: string) => ipcRenderer.invoke('employee:getById', { employeeId }),
    create:             (params: unknown) => ipcRenderer.invoke('employee:create', params),
    update:             (employeeId: string, updates: any) => ipcRenderer.invoke('employee:update', { employeeId, updates }),
    delete:             (employeeId: string) => ipcRenderer.invoke('employee:delete', { employeeId }),
    setPermissions:     (employeeId: string, permissions: any[]) => ipcRenderer.invoke('employee:setPermissions', { employeeId, permissions }),
    getPermissions:     (employeeId: string) => ipcRenderer.invoke('employee:getPermissions', { employeeId }),
    assignAccounts:     (employeeId: string, zaloIds: string[]) => ipcRenderer.invoke('employee:assignAccounts', { employeeId, zaloIds }),
    getAssignedAccounts:(employeeId: string) => ipcRenderer.invoke('employee:getAssignedAccounts', { employeeId }),
    getAccountAccessDetails:(employeeId: string) => ipcRenderer.invoke('employee:getAccountAccessDetails', { employeeId }),
    assignAccountAccessDetails:(employeeId: string, accessDetails: any[]) => ipcRenderer.invoke('employee:assignAccountAccessDetails', { employeeId, accessDetails }),
    getStats:           (employeeId: string, sinceTs?: number, untilTs?: number) => ipcRenderer.invoke('employee:getStats', { employeeId, sinceTs, untilTs }),
    getSessions:        (employeeId: string, limit?: number) => ipcRenderer.invoke('employee:getSessions', { employeeId, limit }),
    login:              (username: string, password: string) => ipcRenderer.invoke('employee:login', { username, password }),
    validateToken:      (token: string) => ipcRenderer.invoke('employee:validateToken', { token }),
    setMode:            (mode: string) => ipcRenderer.invoke('employee:setMode', { mode }),
    getMode:            () => ipcRenderer.invoke('employee:getMode'),
    connectToBoss:      (bossUrl: string, token: string) => ipcRenderer.invoke('employee:connectToBoss', { bossUrl, token }),
    disconnectFromBoss: () => ipcRenderer.invoke('employee:disconnectFromBoss'),
    getConnectionStatus:() => ipcRenderer.invoke('employee:getConnectionStatus'),
    proxyAction:        (channel: string, params: any) => ipcRenderer.invoke('employee:proxyAction', { channel, params }),
    // Groups
    listGroups:         () => ipcRenderer.invoke('employee:listGroups'),
    createGroup:        (name: string, color?: string) => ipcRenderer.invoke('employee:createGroup', { name, color }),
    updateGroup:        (groupId: string, updates: any) => ipcRenderer.invoke('employee:updateGroup', { groupId, updates }),
    deleteGroup:        (groupId: string) => ipcRenderer.invoke('employee:deleteGroup', { groupId }),
    // Analytics
    analyticsComparison:     (sinceTs: number, untilTs: number) => ipcRenderer.invoke('employee:analytics:comparison', { sinceTs, untilTs }),
    analyticsMessageTimeline:(sinceTs: number, untilTs: number) => ipcRenderer.invoke('employee:analytics:messageTimeline', { sinceTs, untilTs }),
    analyticsOnlineTimeline: (sinceTs: number, untilTs: number) => ipcRenderer.invoke('employee:analytics:onlineTimeline', { sinceTs, untilTs }),
    analyticsResponseDist:   (sinceTs: number, untilTs: number) => ipcRenderer.invoke('employee:analytics:responseDistribution', { sinceTs, untilTs }),
    analyticsHourlyActivity: (sinceTs: number, untilTs: number) => ipcRenderer.invoke('employee:analytics:hourlyActivity', { sinceTs, untilTs }),
  },

  // ─── Workspace Management ────────────────────────────────────────
  workspace: {
    list:                 () => ipcRenderer.invoke('workspace:list'),
    getActive:            () => ipcRenderer.invoke('workspace:getActive'),
    create:               (params: unknown) => ipcRenderer.invoke('workspace:create', params),
    update:               (id: string, updates: any) => ipcRenderer.invoke('workspace:update', { id, updates }),
    delete:               (id: string) => ipcRenderer.invoke('workspace:delete', { id }),
    switch:               (id: string) => ipcRenderer.invoke('workspace:switch', { id }),
    isMulti:              () => ipcRenderer.invoke('workspace:isMulti'),
    getDbPath:            (id: string) => ipcRenderer.invoke('workspace:getDbPath', { id }),
    connectRemote:        (id: string, bossUrl: string, token: string) =>
                            ipcRenderer.invoke('workspace:connectRemote', { id, bossUrl, token }),
    disconnectRemote:     (id: string) => ipcRenderer.invoke('workspace:disconnectRemote', { id }),
    getConnectionStatus:  (id: string) => ipcRenderer.invoke('workspace:getConnectionStatus', { id }),
    getAllStatuses:        () => ipcRenderer.invoke('workspace:getAllStatuses'),
    loginRemote:          (bossUrl: string, username: string, password: string) =>
                            ipcRenderer.invoke('workspace:loginRemote', { bossUrl, username, password }),
  },

  // ─── Relay Server (Boss) ──────────────────────────────────────────
  relay: {
    startServer:         (port?: number) => ipcRenderer.invoke('relay:startServer', { port }),
    stopServer:          () => ipcRenderer.invoke('relay:stopServer'),
    getServerStatus:     () => ipcRenderer.invoke('relay:getServerStatus'),
    kickEmployee:        (employeeId: string) => ipcRenderer.invoke('relay:kickEmployee', { employeeId }),
  },

  // ─── Data Sync (Employee) ──────────────────────────────────────────
  sync: {
    requestFullSync:     (zaloIds: string[]) => ipcRenderer.invoke('sync:requestFullSync', { zaloIds }),
    requestDeltaSync:    (sinceTs?: number) => ipcRenderer.invoke('sync:requestDeltaSync', { sinceTs }),
    resetEmployeeDB:     (zaloIds: string[]) => ipcRenderer.invoke('sync:resetEmployeeDB', { zaloIds }),
    getStatus:           () => ipcRenderer.invoke('sync:getStatus'),
    requestMedia:        (filePath: string) => ipcRenderer.invoke('sync:requestMedia', { filePath }),
  },

  // ─── Facebook ─────────────────────────────────────────────────────
  fb: {
    addAccount:          (params: { cookie: string }) => ipcRenderer.invoke('fb:addAccount', params),
    removeAccount:       (params: { accountId: string }) => ipcRenderer.invoke('fb:removeAccount', params),
    updateCookie:        (params: { accountId: string; cookie: string }) => ipcRenderer.invoke('fb:updateCookie', params),
    refreshProfile:      (params: { accountId: string }) => ipcRenderer.invoke('fb:refreshProfile', params),
    getAccounts:         () => ipcRenderer.invoke('fb:getAccounts'),
    connect:             (params: { accountId: string }) => ipcRenderer.invoke('fb:connect', params),
    disconnect:          (params: { accountId: string }) => ipcRenderer.invoke('fb:disconnect', params),
    checkHealth:         (params: { accountId: string }) => ipcRenderer.invoke('fb:checkHealth', params),
    sendMessage:         (params: unknown) => ipcRenderer.invoke('fb:sendMessage', params),
    sendAttachment:      (params: unknown) => ipcRenderer.invoke('fb:sendAttachment', params),
    sendAttachments:     (params: unknown) => ipcRenderer.invoke('fb:sendAttachments', params),
    unsendMessage:       (params: unknown) => ipcRenderer.invoke('fb:unsendMessage', params),
    addReaction:         (params: unknown) => ipcRenderer.invoke('fb:addReaction', params),
    getThreads:          (params: unknown) => ipcRenderer.invoke('fb:getThreads', params),
    getMessages:         (params: unknown) => ipcRenderer.invoke('fb:getMessages', params),
    markAsRead:          (params: unknown) => ipcRenderer.invoke('fb:markAsRead', params),
    changeThreadName:    (params: unknown) => ipcRenderer.invoke('fb:changeThreadName', params),
    changeThreadEmoji:   (params: unknown) => ipcRenderer.invoke('fb:changeThreadEmoji', params),
    changeNickname:      (params: unknown) => ipcRenderer.invoke('fb:changeNickname', params),
    loginWithCredentials:(params: unknown) => ipcRenderer.invoke('fb:loginWithCredentials', params),
  },

  // ─── ERP ─────────────────────────────────────────────────────────
  erp: {
    // Projects
    projectList:        (params?: unknown) => ipcRenderer.invoke('erp:project:list', params),
    projectCreate:      (params: unknown) => ipcRenderer.invoke('erp:project:create', params),
    projectUpdate:      (params: unknown) => ipcRenderer.invoke('erp:project:update', params),
    projectDelete:      (params: unknown) => ipcRenderer.invoke('erp:project:delete', params),
    // Tasks
    taskList:           (params?: unknown) => ipcRenderer.invoke('erp:task:list', params),
    taskGet:            (params: unknown) => ipcRenderer.invoke('erp:task:get', params),
    taskCreate:         (params: unknown) => ipcRenderer.invoke('erp:task:create', params),
    taskUpdate:         (params: unknown) => ipcRenderer.invoke('erp:task:update', params),
    taskUpdateStatus:   (params: unknown) => ipcRenderer.invoke('erp:task:updateStatus', params),
    taskAssign:         (params: unknown) => ipcRenderer.invoke('erp:task:assign', params),
    taskDelete:         (params: unknown) => ipcRenderer.invoke('erp:task:delete', params),
    taskAddChecklist:   (params: unknown) => ipcRenderer.invoke('erp:task:addChecklist', params),
    taskToggleChecklist:(params: unknown) => ipcRenderer.invoke('erp:task:toggleChecklist', params),
    taskAddComment:     (params: unknown) => ipcRenderer.invoke('erp:task:addComment', params),
    taskEditComment:    (params: unknown) => ipcRenderer.invoke('erp:task:editComment', params),
    taskDeleteComment:  (params: unknown) => ipcRenderer.invoke('erp:task:deleteComment', params),
    taskListMyInbox:    (params: unknown) => ipcRenderer.invoke('erp:task:listMyInbox', params),
    // Calendar
    calendarListEvents: (params: unknown) => ipcRenderer.invoke('erp:calendar:listEvents', params),
    calendarCreate:     (params: unknown) => ipcRenderer.invoke('erp:calendar:createEvent', params),
    calendarUpdate:     (params: unknown) => ipcRenderer.invoke('erp:calendar:updateEvent', params),
    calendarDelete:     (params: unknown) => ipcRenderer.invoke('erp:calendar:deleteEvent', params),
    calendarCheckConflict:(params: unknown) => ipcRenderer.invoke('erp:calendar:checkConflict', params),
    // Notes
    noteListFolders:    (params: unknown) => ipcRenderer.invoke('erp:note:listFolders', params),
    noteCreateFolder:   (params: unknown) => ipcRenderer.invoke('erp:note:createFolder', params),
    noteRenameFolder:   (params: unknown) => ipcRenderer.invoke('erp:note:renameFolder', params),
    noteDeleteFolder:   (params: unknown) => ipcRenderer.invoke('erp:note:deleteFolder', params),
    noteList:           (params?: unknown) => ipcRenderer.invoke('erp:note:list', params),
    noteGet:            (params: unknown) => ipcRenderer.invoke('erp:note:get', params),
    noteCreate:         (params: unknown) => ipcRenderer.invoke('erp:note:create', params),
    noteUpdate:         (params: unknown) => ipcRenderer.invoke('erp:note:update', params),
    noteDelete:         (params: unknown) => ipcRenderer.invoke('erp:note:delete', params),
    notePin:            (params: unknown) => ipcRenderer.invoke('erp:note:pin', params),
    noteListTags:       () => ipcRenderer.invoke('erp:note:listTags'),
    noteCreateTag:      (params: unknown) => ipcRenderer.invoke('erp:note:createTag', params),
    noteAddTag:         (params: unknown) => ipcRenderer.invoke('erp:note:addTag', params),
    noteRemoveTag:      (params: unknown) => ipcRenderer.invoke('erp:note:removeTag', params),
    noteVersions:       (params: unknown) => ipcRenderer.invoke('erp:note:versions', params),
    noteRestoreVersion: (params: unknown) => ipcRenderer.invoke('erp:note:restoreVersion', params),
    noteShare:          (params: unknown) => ipcRenderer.invoke('erp:note:share', params),
    noteListShares:     (params: unknown) => ipcRenderer.invoke('erp:note:listShares', params),
    // Task watchers/dependencies (Phase 2)
    taskAddWatcher:     (params: unknown) => ipcRenderer.invoke('erp:task:addWatcher', params),
    taskRemoveWatcher:  (params: unknown) => ipcRenderer.invoke('erp:task:removeWatcher', params),
    taskAddDependency:  (params: unknown) => ipcRenderer.invoke('erp:task:addDependency', params),
    taskRemoveDependency:(params: unknown) => ipcRenderer.invoke('erp:task:removeDependency', params),
    // Calendar respond (Phase 2)
    calendarRespond:    (params: unknown) => ipcRenderer.invoke('erp:calendar:respond', params),
    // HRM (Phase 2)
    departmentList:     () => ipcRenderer.invoke('erp:department:list'),
    departmentCreate:   (params: unknown) => ipcRenderer.invoke('erp:department:create', params),
    departmentUpdate:   (params: unknown) => ipcRenderer.invoke('erp:department:update', params),
    departmentDelete:   (params: unknown) => ipcRenderer.invoke('erp:department:delete', params),
    positionList:       () => ipcRenderer.invoke('erp:position:list'),
    positionCreate:     (params: unknown) => ipcRenderer.invoke('erp:position:create', params),
    positionUpdate:     (params: unknown) => ipcRenderer.invoke('erp:position:update', params),
    positionDelete:     (params: unknown) => ipcRenderer.invoke('erp:position:delete', params),
    employeeGetProfile: (params: unknown) => ipcRenderer.invoke('erp:employee:getProfile', params),
    employeeUpdateProfile:(params: unknown) => ipcRenderer.invoke('erp:employee:updateProfile', params),
    employeeListByDepartment:(params: unknown) => ipcRenderer.invoke('erp:employee:listByDepartment', params),
    employeeDeleteProfile:(params: unknown) => ipcRenderer.invoke('erp:employee:deleteProfile', params),
    attendanceCheckIn:  (params: unknown) => ipcRenderer.invoke('erp:attendance:checkIn', params),
    attendanceCheckOut: (params: unknown) => ipcRenderer.invoke('erp:attendance:checkOut', params),
    attendanceToday:    () => ipcRenderer.invoke('erp:attendance:today'),
    attendanceList:     (params: unknown) => ipcRenderer.invoke('erp:attendance:list', params),
    leaveCreate:        (params: unknown) => ipcRenderer.invoke('erp:leave:create', params),
    leaveListMy:        () => ipcRenderer.invoke('erp:leave:listMy'),
    leaveListPending:   () => ipcRenderer.invoke('erp:leave:listPending'),
    leaveDecide:        (params: unknown) => ipcRenderer.invoke('erp:leave:decide', params),
    leaveCancel:        (params: unknown) => ipcRenderer.invoke('erp:leave:cancel', params),
    licenseSeatStatus:  () => ipcRenderer.invoke('erp:license:seatStatus'),
    // Notifications
    notifyListInbox:    (params: unknown) => ipcRenderer.invoke('erp:notify:listInbox', params),
    notifyMarkRead:     (params: unknown) => ipcRenderer.invoke('erp:notify:markRead', params),
    notifyMarkAllRead:  (params: unknown) => ipcRenderer.invoke('erp:notify:markAllRead', params),
    notifyUnreadCount:  (params: unknown) => ipcRenderer.invoke('erp:notify:unreadCount', params),
  },
  on: (channel: string, callback: (...args: unknown[]) => void) => {
    const validChannels = [
      'event:message',
      'event:connected',
      'event:disconnected',
      'event:reaction',
      'event:friendRequest',
      'event:friendAccepted',
      'event:groupEvent',
      'event:groupInfoUpdate',
      'event:undo',
      'event:delete',
      'event:reminder',
      'event:localPath',
      'event:listenerDead',
      'event:pinsUpdated',
      'event:typing',
      'event:seen',
      'qr:update',
      'update:available',
      'update:progress',
      'update:downloaded',
      'update:error',
      'app:openThread',
      'app:windowFocus',
      'app:drawBadge',
      'crm:queueUpdate',
      'crm:queueStatus',
      'crm:campaignDone',
      'workflow:executed',
      'db:copyProgress',
      'integration:webhook',
      'integration:payment',
      'tunnel:changed',
      'relay:employeeListUpdate',
      'relay:messageSentByEmployee',
      'sync:progress',
      'workspace:switched',
      'workspace:connectionStatus',
      'workspace:initialState',
      'workspace:accountAccessUpdate',
      // ─── Facebook events ─────────────────────────────────────────────
      'fb:onMessage',
      'fb:onReaction',
      'fb:onUnsend',
      'fb:onDisconnect',
      'fb:onReconnect',
      'fb:onConnectionStatus',
      // ─── ERP events ──────────────────────────────────────────────────
      'erp:event:taskCreated',
      'erp:event:taskUpdated',
      'erp:event:taskDeleted',
      'erp:event:commentAdded',
      'erp:event:projectCreated',
      'erp:event:projectUpdated',
      'erp:event:projectDeleted',
      'erp:event:calendarEventCreated',
      'erp:event:calendarEventUpdated',
      'erp:event:calendarEventDeleted',
      'erp:event:noteCreated',
      'erp:event:noteUpdated',
      'erp:event:noteDeleted',
      'erp:event:notification',
      'erp:event:reminder',
      'erp:event:leaveCreated',
      'erp:event:leaveDecided',
      'erp:event:attendanceUpdated',
      'erp:event:noteShared',
      'erp:event:departmentUpdated',
      'erp:event:employeeProfileUpdated',
    ];
    if (validChannels.includes(channel)) {
      const subscription = (_event: unknown, ...args: unknown[]) => callback(...args);
      ipcRenderer.on(channel, subscription);
      return () => ipcRenderer.removeListener(channel, subscription);
    }
    return () => {};
  },

  removeAllListeners: (channel: string) => {
    ipcRenderer.removeAllListeners(channel);
  },
});

contextBridge.exposeInMainWorld('licenseAPI', {
  verify: (email: string, licenseKey: string | null) => ipcRenderer.invoke('license:verify', { email, licenseKey }),
  register: (data: unknown) => ipcRenderer.invoke('license:register', data),
  activateAfterRegister: (email: string, licenseKey: string) => ipcRenderer.invoke('license:activateAfterRegister', { email, licenseKey }),
  get: () => ipcRenderer.invoke('license:get'),
  logout: () => ipcRenderer.invoke('license:logout')
});

