-- Create promo_campaigns table for flexible promotional campaigns
CREATE TABLE IF NOT EXISTS public.promo_campaigns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_code TEXT UNIQUE NOT NULL,
    title TEXT NOT NULL,
    banner_text TEXT,
    start_at TIMESTAMPTZ NOT NULL,
    end_at TIMESTAMPTZ NOT NULL,
    is_active BOOLEAN DEFAULT true,
    rules JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.promo_campaigns ENABLE ROW LEVEL SECURITY;

-- Allow public read access to active promotional campaigns
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'promo_campaigns' AND policyname = 'Allow public read access to active promos'
    ) THEN
        CREATE POLICY "Allow public read access to active promos" ON public.promo_campaigns
            FOR SELECT USING (is_active = true AND NOW() BETWEEN start_at AND end_at);
    END IF;
END $$;

-- Insert initial August 2026 Promo Campaign (Mua X tháng tặng Y tháng)
INSERT INTO public.promo_campaigns (campaign_code, title, banner_text, start_at, end_at, is_active, rules)
VALUES (
    'promo_august_2026',
    'Chương Trình Tri Ân Tháng 8 - Nhân Đôi Thời Hạn Sử Dụng',
    'THÁNG 8 — NHÂN ĐÔI THỜI HẠN: mua 6 tháng dùng 12, mua 12 tháng dùng 24.',
    '2026-08-01 00:00:00+07',
    '2026-08-31 23:59:59+07',
    true,
    '{
        "solo_6m": { "bonus_months": 6, "total_months": 12, "badge": "Tặng +6 tháng (Tổng 12M)" },
        "solo_12m": { "bonus_months": 12, "total_months": 24, "badge": "Tặng +12 tháng (Tổng 24M)" },
        "team_12m": { "bonus_months": 12, "total_months": 24, "badge": "Tặng +12 tháng cho Team (Tổng 24M)" }
    }'::jsonb
)
ON CONFLICT (campaign_code) 
DO UPDATE SET 
    title = EXCLUDED.title,
    banner_text = EXCLUDED.banner_text,
    start_at = EXCLUDED.start_at,
    end_at = EXCLUDED.end_at,
    is_active = EXCLUDED.is_active,
    rules = EXCLUDED.rules;
