-- Create plans table if not exists
CREATE TABLE IF NOT EXISTS public.plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_code TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    amount BIGINT NOT NULL DEFAULT 0,
    description TEXT,
    type TEXT DEFAULT 'solo',
    is_popular BOOLEAN DEFAULT false,
    is_active BOOLEAN DEFAULT true,
    sort_order INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS & allow public read access
ALTER TABLE public.plans ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'plans' AND policyname = 'Allow public read access to active plans'
    ) THEN
        CREATE POLICY "Allow public read access to active plans" ON public.plans
            FOR SELECT USING (is_active = true);
    END IF;
END $$;

-- Insert initial plans
INSERT INTO public.plans (plan_code, name, amount, description, type, is_popular, is_active, sort_order)
VALUES 
    ('solo_6m',       'Gói Solo 6 tháng',    2450000,  'Sử dụng đầy đủ trong 6 tháng (1 Máy BOSS)', 'solo', false, true, 1),
    ('solo_12m',      'Gói Solo 12 tháng',   4450000,  'Lựa chọn tối ưu cho 1 năm (1 Máy BOSS)',    'solo', true,  true, 2),
    ('solo_lifetime', 'Gói Solo Vĩnh viễn',  7450000,  'Thanh toán một lần, dùng trọn đời',         'solo', false, true, 3),
    ('team_6m',       'Gói Team 6 tháng',    4900000,  '1 Máy BOSS + Tối đa 5 Máy Nhân viên',       'team', false, true, 4),
    ('team_12m',      'Gói Team 12 tháng',   8900000,  '1 Máy BOSS + Tối đa 5 Máy Nhân viên',       'team', true,  true, 5),
    ('team_lifetime', 'Gói Team Vĩnh viễn',  14900000, '1 Máy BOSS + Tối đa 20 Máy Nhân viên',      'team', false, true, 6)
ON CONFLICT (plan_code) 
DO UPDATE SET 
    name = EXCLUDED.name,
    amount = EXCLUDED.amount,
    description = EXCLUDED.description,
    type = EXCLUDED.type,
    is_popular = EXCLUDED.is_popular,
    is_active = EXCLUDED.is_active,
    sort_order = EXCLUDED.sort_order;
